# Generated by Django 4.1.5 on 2023-01-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('passwd', models.CharField(default='', max_length=20, verbose_name='密码')),
            ],
        ),
    ]
