# Generated by Django 4.1.5 on 2023-01-08 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userma',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userma',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userma',
            name='passwd',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userma',
            name='user',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
