# Generated by Django 4.1.5 on 2023-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0002_userma_created_time_userma_updata_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userma',
            name='passwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
