# Generated by Django 4.1.5 on 2023-01-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(default='', max_length=32)),
                ('summary', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='goods', verbose_name='商品照片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsdata.goods')),
            ],
        ),
    ]
