# Generated by Django 4.1.5 on 2023-01-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(null=True, upload_to='user_image', verbose_name='用户头像'),
        ),
    ]
